services:
  web:
    build: .
    container_name: crm_web
    restart: always
    env_file: .env.production
    networks:
      - reverse-proxy-net
      - mongo-net

networks:
  reverse-proxy-net:
    external: true
  mongo-net:
    external: true
